development:
  adapter: em_mysql2
  database: rails_async_development
  username: root
  pool: 250
  timeout: 5000

test:
  adapter: em_mysql2
  database: rails_async_test
  username: root
  pool: 5
  timeout: 5000

